FROM bkaiserdevops/ubuntu_22_base:1

WORKDIR /var/www/html

RUN apt-get install -y \
    libsasl2-dev \
    libssl-dev \
    libmariadb-dev \
    apache2 \
    apache2-dev \
    apache2-utils \
    ssl-cert \

